---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user: serge2029
    group_name: devops
  vars_files:
    - variables.yml

  tasks:
    - name: Check the time
      command: dateojljjbkk
#      when: ansible_distribution == "Serge" or ansible_processor_nproc == 2
    - name: create user serge
      user: 
         name: "{{user}}"
         comment: Serge Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: install package
      package:
        name: "{{pkg_name}}"
        state: present